### PR TITLE
Fixing #126, possibly breaking compatibility with Django<=1.7

### PR DESCRIPTION
**Pull request by int-ua**
It should be possible to implement compatibility but I'm not interested in this at all.

### CODE REVIEW

**Comment by int-ua** [comment]
#126

**Comment by camilonova** [comment]
@aclark4life seems we can't forget projects using django < 1.7 what do you think?

**Comment by aclark4life** [comment]
I would say we *can* drop 1.7 now, see: https://www.djangoproject.com/download/#supported-versions

**Comment by camilonova** [comment]
Thanks

**Pull request merged**
