### PR TITLE
Added JSON response type.

### PR DESCRIPTION
**Pull request by mullakhmetov**
Based on #114

### CODE REVIEW

**Comment by mullakhmetov** [comment]
Should I fix it and write my own format_timedelta implementation or we can add babel as dependency?

**Comment by camilonova** [comment]
@mullakhmetov it is possible to not use babel?

**Comment by mullakhmetov** [comment]
It's hard to get so natural humanize time delta format which babel provides. It allows to round delta, supports locales, etc.:
`>>>format_timedelta(timedelta(days=1, hours=22))
u'2 days'
>>>format_timedelta(timedelta(minutes=60), locale='ES_es')
1 hora
>>>format_timedelta(timedelta(hours=1), add_direction=True)
u'in 1 hour''
>>>format_timedelta(timedelta(hours=3), format='narrow', locale='en')
u'3h'`
Also I'd like to add feature allows to get lock left time also in natural format:
"Account locked: too many login attempts. Please try again later in an hour."
Babel will help me.

**Comment by camilonova** [comment]
I would like more feedback from @django-pci/owners

**Comment by mullakhmetov** [comment]
I can refuse to use babel for humanize delta in response and replace it by coolof time in iso format like "P4DT12H30M17S" or whatever you want.

**Comment by camilonova** [comment]
@mullakhmetov good idea, please do it. Also please check the travis build passes.

**Comment by camilonova** [comment]
Beautiful. Thanks

**Comment by BeOleg** [comment]
There is actually a problem where view logic is still executed despite lockout, and I have test to prove it.

**Pull request merged**
